# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-15 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myBlog', '0002_auto_20180715_1218'),
        ('comment', '0002_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('text', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBlog.Post')),
            ],
        ),
    ]
