# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-15 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
