# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-15 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_comment_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='view',
        ),
    ]
